/* 
  Usage:
  node ./wc.js file1
  node ./wc.js -l file1
  node ./wc.js -c file1
  node ./wc.js -w file1
  node ./wc.js file1 file2
  node ./wc.js -lw file1 [file2]...
  node ./wc.js -wl file1 [file2]...
  node ./wc.js -cl file1 [file2]...
  node ./wc.js -lc file1 [file2]...
  node ./wc.js -wc file1 [file2]...
  node ./wc.js -cw file1 [file2]...
  node ./wc.js -lcw file1 [file2]...
  node ./wc.js -lwc file1 [file2]...
  node ./wc.js -wcc file1 [file2]...
  node ./wc.js -wlc file1 [file2]...
  node ./wc.js -wlc file1 [file2]...
  node ./wc.js -l -w file1 [file2]...
  node ./wc.js -l -c file1 [file2]...
  node ./wc.js -w -c file1 [file2]...
  node ./wc.js -w -l file1 [file2]...
  node ./wc.js -c -l file1 [file2]...
  node ./wc.js -c -w file1 [file2]...
  node ./wc.js -l -c -w file1 [file2]...
  node ./wc.js -l -w -c file1 [file2]...
  node ./wc.js -w -l -c file1 [file2]...
  node ./wc.js -w -c -l file1 [file2]...
  node ./wc.js -c -w -l file1 [file2]...
  node ./wc.js -c -l -w file1 [file2]...
*/
